### ISSUE TITLE
Bugsnag

### ISSUE THREAD

**Issue by IzzySoft** [umer0586/SensorServer#10]
Last release now includes Bugsnag, which triggered an alert here in my repo (where [your app is listed](https://apt.izzysoft.de/fdroid/index/apk/github.umer0586). Is it configured opt-in, or transmitting data by default? What data is transmitted, and is that transparent to the user (e.g. details are shown and user then can decide to send or not)?

**Comment by umer0586** [comment]
No its not configured opt-in, sends data by default  (thrown exceptions). I am not planning to integrate bugsnag in future release, i am just testing there 14 days trial which they have given for free.

**Comment by IzzySoft** [comment]
Ah, if it goes away with the next release of course no need to bother. I'll then for now apply the `Tracking` anti-feature (else I get an alert every day) – and once an update removes Bugsnag again I'll receive another alert and will remove the AF again. Thanks for the details!

**Comment by umer0586** [comment]
Next release will be uploaded in 8-9 days. Untill then you can mark Tracking anti-feature.

**Comment by IzzySoft** [comment]
Done. Will automatically remove it once the update without Bugsnag comes in (my updater will inform me about the dropped tracker). Thanks!

Oh: and feel free to close the issue when it's through :wink:

**Comment by IzzySoft** [comment]
Yay, thanks! As predicted, my updater just informed me to remove the `Tracking` flag – and so I did. Will be gone with tomorrow's sync then.
