### ISSUE TITLE
Use material you navigation bar

### ISSUE THREAD

**Issue by xmha97** [umer0586/SensorServer#12]
Please use material you navigation bar.

![Screenshot_2022-11-27-21-37-00-763_com.zionhuang.music.jpg](https://user-images.githubusercontent.com/23485114/204152301-e366f6fc-11d8-4d94-b82d-d229299cfc35.jpg)

**Comment by umer0586** [comment]
I think its not needed

**Comment by xmha97** [comment]
If you think this change will take too much of your time, please close it.
