### ISSUE TITLE
Not working over WiFi

### ISSUE THREAD

**Issue by alexschultze** [umer0586/SensorServer#17]
```
=========== RESTART: \wsocket_client.py ==========
error occurred
[WinError 10061] No connection could be made because the target machine actively refused it
connection close
close code :  None
reason :  None
```

Maybe phone firewall have a reject rule and thus do not work well as servers.

I have tried with two devices (Samsung and Huawei). I have tried different ports. I am on a local Wireless LAN.

**Comment by umer0586** [comment]
In my example I used Ip 192.168.0.102 but your android device you may get different IP when you press start button. 
Just make sure that your client script is using correct Ip and Port shown in device

**Comment by umer0586** [comment]
@alexschultze still having issue??

**Comment by alexschultze** [comment]
I have chosen the correct IP address, as I know devices IP through router, and have ping it with success.
Whats your tested android version?

**Comment by alexschultze** [comment]
If this works for you (and others) I suggest closing this issue, as it must be something on my side.

**Comment by umer0586** [comment]
Okay but you can try hotspot option. 
I am closing this for now...
