### ISSUE TITLE
sonar sensor

### ISSUE THREAD

**Issue by zenbooster** [umer0586/SensorServer#18]
Could you add sonar as a sensor, like in the "Sleep As Android" program?
(For these purposes, they use a built-in speaker, microphone and frequencies above 20 kHz.)

**Comment by umer0586** [comment]
This seems to be a good idea but I haven't heard about such method in Android environment. 
Sleep As Android documentation says 
> Our invention — the sonar — uses your phone’s speaker and microphone to sense movement in the near surroundings

> During tracking with sonar the phone produces ultrasonic signal (which cannot be heard by most). Even tiny movements distort the reflected signal which allows us to track them when we record them with the microphone.

This seems quite challenging and hard to implement as device need to produce ultrasonic waves (through speakers) and checking the distorted reflected waves (through microphone) to detect presence of object in surrounding. So a lot of maths would be required as sound comes with noise.
