### ISSUE TITLE
Usb serial

### ISSUE THREAD

**Issue by Shuvadip-Ghosh** [umer0586/SensorServer#19]
Is there any way to send the Gyroscope data using usb serial communication instead of websockets. Because the latency is too much. And I am on a project that requires low latency.

**Comment by umer0586** [comment]
Sorry this project is only based on websockets. For low latency set sampling rate to 0 from settings before starting server

**Comment by umer0586** [comment]
@Shuvadip-Ghosh any further query?

**Comment by Shuvadip-Ghosh** [comment]
No bro thank you
