### ISSUE TITLE
Websocket connection failed

### ISSUE THREAD

**Issue by yogeshbndm** [umer0586/SensorServer#2]
When i tried to make a client and establish the connection, it shows "connection failed". Can you suggest me the possible reason for this.

**Comment by umer0586** [comment]
> When i tried to make a client and establish the connection, it shows "connection failed". Can you suggest me the possible reason for this.

Is there any further information along with `connection failed` ?. Make sure client and server are connected to the same network .

In which language you are writing Websocket client  ? Have you tested the app with any of **Websocket testing tools** available (like http://livepersoninc.github.io/ws-test-page/)

**Comment by yogeshbndm** [comment]
issue fixed... the problem was that the client and server were not
connected to the same network...

**Comment by Dantrix846** [comment]
> > When i tried to make a client and establish the connection, it shows "connection failed". Can you suggest me the possible reason for this.
> 
> @yogeshbndm Is there any further information along with `connection failed` ?. Make sure client and server are connected to the same network and client is connecting using valid URL.
> 
> In which language you are writing Websocket client ? Have you tested the app with any of **Websocket testing tools** available (like http://livepersoninc.github.io/ws-test-page/)

i have everything @ the same network, but it still doesnt work even in the ws test page

**Comment by umer0586** [comment]
@Dantrix846 make sure you typed url correctly

**Comment by Dantrix846** [comment]
it was and is typed correctly. Idk what could be wrong.

čt 27. 10. 2022 v 9:26 odesílatel Umer Farooq ***@***.***>
napsal:

**Comment by umer0586** [comment]
@Dantrix846 you must be doing something wrong. If your PC and phone are on same wifi network then specifying proper ip and port in websocket client should successfully connect to app.
