### ISSUE TITLE
Unable to open app in Android

### ISSUE THREAD

**Issue by srbhptl39** [umer0586/SensorServer#23]
I have been trying to open the app [Sensor Server v4.0.0](https://github.com/umer0586/SensorServer/releases/tag/v4.0.0), but it closes immediately. 
Version v3.2.1 works fine

Android Version 13
Oneplus device

**Comment by umer0586** [comment]
The next release of the app will include a cash reporting library. Once this is integrated, you will be able to send (crash) logs here.

Have you tested v4.0.0 on some other device with Android Version 13 ?

**Comment by umer0586** [comment]
I have tested the app on emulator with android 13 and it doesn't crash on open. Have you tested v4.0.0 on other devices having version 13?

**Comment by srbhptl39** [comment]
yes tested in other android 13 version also, it seems to crash. Emulators might not support all sensors which might not be causing it to crash, not sure there.

**Comment by umer0586** [comment]
> yes tested in other android 13 version also, it seems to crash. Emulators might not support all sensors which might not be causing it to crash, not sure there.

The app currently does not check for sensors upon opening. The app crashes when opened, indicates that there may be some other issue. I am currently in the process of migrating the code to Kotlin. Once that is complete, I will investigate this issue further.

**Comment by umer0586** [comment]
> Can you provide a test version if the integration is complete?


1. Download the installation file [SensorServer-v5.0.0-beta.1.zip](https://github.com/umer0586/SensorServer/files/11683446/SensorServer-v5.0.0-beta.1.zip).
2. After installing, if the SensorServer crashes, it will automatically open your email client.
3. The crash log will be populated in the email body.
4. You have the option to either send the log via email or simply copy and paste it here.

Since GitHub does not allow uploading APK files here, I have provided a ZIP file instead. Please extract APK from ZIP file.

**Comment by srbhptl39** [comment]
`{"REPORT_ID":"2edd5d5e-df8c-435a-8b3d-4651ae0dea25","APP_VERSION_CODE":21,"APP_VERSION_NAME":"5.0.0-beta.1","PACKAGE_NAME":"github.umer0586.sensorserver","FILE_PATH":"\/data\/user\/0\/github.umer0586.sensorserver\/files","PHONE_MODEL":"LE2101","BRAND":"OnePlus","PRODUCT":"OnePlus9R_IND","ANDROID_VERSION":"13","BUILD":{"BOARD":"kona","BOOTLOADER":"unknown","BRAND":"OnePlus","CPU_ABI":"arm64-v8a","CPU_ABI2":"","DEVICE":"OnePlus9R","DISPLAY":"LE2101_13.1.0.500(EX01)","FINGERPRINT":"OnePlus\/OnePlus9R_IND\/OnePlus9R:13\/RKQ1.211119.001\/R.103dfa6-1-58fae:user\/release-keys","HARDWARE":"qcom","HOST":"dg02-pool03-kvm246","HW_TIMEOUT_MULTIPLIER":1,"ID":"RKQ1.211119.001","IS_ARC":false,"IS_DEBUGGABLE":false,"IS_EMULATOR":false,"IS_ENG":false,"IS_TREBLE_ENABLED":true,"IS_USER":true,"IS_USERDEBUG":false,"MANUFACTURER":"OnePlus","MODEL":"LE2101","ODM_SKU":"unknown","PERMISSIONS_REVIEW_REQUIRED":true,"PRODUCT":"OnePlus9R_IND","RADIO":"unknown","SKU":"unknown","SOC_MANUFACTURER":"Qualcomm","SOC_MODEL":"SM8250","SUPPORTED_32_BIT_ABIS":["armeabi-v7a","armeabi"],"SUPPORTED_64_BIT_ABIS":["arm64-v8a"],"SUPPORTED_ABIS":["arm64-v8a","armeabi-v7a","armeabi"],"TAGS":"release-keys","TIME":1683259406000,"TYPE":"user","UNKNOWN":"unknown","USER":"root","VERSION":{"ACTIVE_CODENAMES":[],"BASE_OS":"","CODENAME":"REL","DEVICE_INITIAL_SDK_INT":30,"INCREMENTAL":"R.103dfa6-1-58fae","KNOWN_CODENAMES":"{HoneycombMr1, HoneycombMr2, Lollipop, Kitkat, Tiramisu, Gingerbread, Cupcake, IceCreamSandwichMr1, JellyBean, IceCreamSandwich, LollipopMr1, M, N, O, P, Q, R, S, Sv2, Base, NMr1, OMr1, JellyBeanMr1, JellyBeanMr2, Donut, Froyo, GingerbreadMr1, EclairMr1, Honeycomb, Eclair01, KitkatWatch, Base11, Eclair}","MEDIA_PERFORMANCE_CLASS":0,"MIN_SUPPORTED_TARGET_SDK_INT":23,"PREVIEW_SDK_FINGERPRINT":"REL","PREVIEW_SDK_INT":0,"RELEASE":"13","RELEASE_OR_CODENAME":"13","RELEASE_OR_PREVIEW_DISPLAY":"13","RESOURCES_SDK_INT":33,"SDK":"33","SDK_INT":33,"SECURITY_PATCH":"2023-04-05"}},"TOTAL_MEM_SIZE":115823456256,"AVAILABLE_MEM_SIZE":45418471424,"BUILD_CONFIG":{"APPLICATION_ID":"github.umer0586.sensorserver","BUILD_TYPE":"debug","DEBUG":true,"VERSION_CODE":21,"VERSION_NAME":"5.0.0-beta.1"},"CUSTOM_DATA":{},"IS_SILENT":false,"STACK_TRACE":"java.lang.RuntimeException: Unable to start activity ComponentInfo{github.umer0586.sensorserver\/github.umer0586.sensorserver.activities.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3876)\n\tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)\n\tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)\n\tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n\tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n\tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)\n\tat android.os.Handler.dispatchMessage(Handler.java:106)\n\tat android.os.Looper.loopOnce(Looper.java:240)\n\tat android.os.Looper.loop(Looper.java:351)\n\tat android.app.ActivityThread.main(ActivityThread.java:8399)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)\nCaused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.\n\tat androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:630)\n\tat androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:185)\n\tat github.umer0586.sensorserver.activities.MainActivity.onCreate(MainActivity.kt:60)\n\tat android.app.Activity.performCreate(Activity.java:8422)\n\tat android.app.Activity.performCreate(Activity.java:8395)\n\tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)\n\tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3849)\n\t... 12 more\n","INITIAL_CONFIGURATION":{"assetsSeq":0,"colorMode":10,"compatScreenHeightDp":680,"compatScreenWidthDp":320,"compatSmallestScreenWidthDp":320,"densityDpi":480,"fontScale":0.9,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_GB","mcc":405,"mnc":54,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":765,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":360,"seq":11042,"smallestScreenWidthDp":360,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_YES","userSetLocale":false,"windowConfiguration":"{ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 103 - 1080, 2400) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0}","mOplusExtraConfiguration":"mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1174052744031371281, mMaterialColor= 2, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 31f4, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 8.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mBurmeseFontFlag= 2, mFlag= 0"},"CRASH_CONFIGURATION":{"assetsSeq":0,"colorMode":10,"compatScreenHeightDp":680,"compatScreenWidthDp":320,"compatSmallestScreenWidthDp":320,"densityDpi":480,"fontScale":0.9,"fontWeightAdjustment":0,"hardKeyboardHidden":"HARDKEYBOARDHIDDEN_YES","keyboard":"KEYBOARD_NOKEYS","keyboardHidden":"KEYBOARDHIDDEN_NO","locale":"en_GB","mcc":405,"mnc":54,"navigation":"NAVIGATION_NONAV","navigationHidden":"NAVIGATIONHIDDEN_YES","orientation":"ORIENTATION_PORTRAIT","screenHeightDp":765,"screenLayout":"SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO","screenWidthDp":360,"seq":11042,"smallestScreenWidthDp":360,"touchscreen":"TOUCHSCREEN_FINGER","uiMode":"UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_YES","userSetLocale":false,"windowConfiguration":"{ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 103 - 1080, 2400) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0}","mOplusExtraConfiguration":"mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 1174052744031371281, mMaterialColor= 2, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 31f4, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 8.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 4096, mBurmeseFontFlag= 2, mFlag= 0"},"DISPLAY":{"0":{"currentSizeRange":{"smallest":[1080,977],"largest":[2297,2297]},"flags":"FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE+FLAG_TRUSTED","metrics":{"density":3,"densityDpi":480,"scaledDensity":"x3.0","widthPixels":1080,"heightPixels":2297,"xdpi":391.885009765625,"ydpi":403.7080078125},"realMetrics":{"density":3,"densityDpi":480,"scaledDensity":"x3.0","widthPixels":1080,"heightPixels":2400,"xdpi":391.885009765625,"ydpi":403.7080078125},"name":"Built-in Screen","realSize":[1080,2400],"rectSize":[0,0,1080,2297],"size":[1080,2297],"rotation":"ROTATION_0","isValid":true,"orientation":0,"refreshRate":120.00000762939453,"height":2297,"width":1080,"pixelFormat":1}},"USER_COMMENT":null,"USER_EMAIL":"N\/A","USER_APP_START_DATE":"2023-06-08T20:53:05.381+05:30","USER_CRASH_DATE":"2023-06-08T20:53:05.567+05:30","DUMPSYS_MEMINFO":"","LOGCAT":"06-08 20:53:05.206 D\/nativeloader(19927): Configuring classloader-namespace for other apk \/system_ext\/framework\/androidx.window.extensions.jar. target_sdk_version=33, uses_libraries=ALL, library_path=\/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/lib\/arm64, permitted_path=\/data:\/mnt\/expand:\/data\/user\/0\/github.umer0586.sensorserver\n06-08 20:53:05.206 D\/nativeloader(19927): Extending system_exposed_libraries: [libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so](http://libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libsloganjni.oplus.so:libsupernight.oplus.so:libupdateprof.qti.so:libqoc.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so/)\n06-08 20:53:05.212 D\/nativeloader(19927): Configuring classloader-namespace for other apk \/system_ext\/framework\/androidx.window.sidecar.jar. target_sdk_version=33, uses_libraries=ALL, library_path=\/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/lib\/arm64, permitted_path=\/data:\/mnt\/expand:\/data\/user\/0\/github.umer0586.sensorserver\n06-08 20:53:05.212 D\/nativeloader(19927): Extending system_exposed_libraries: [libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libSloganJni.oplus.so:libsuperNight.oplus.so:libupdateprof.qti.so:libQOC.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so](http://libbinauralrenderer_wrapper.qti.so:libhoaeffects.qti.so:libsloganjni.oplus.so:libsupernight.oplus.so:libupdateprof.qti.so:libqoc.qti.so:libthermalclient.qti.so:libdiag_system.qti.so:libqape.qti.so:liblistenjni.qti.so/)\n06-08 20:53:05.214 W\/ziparchive(19927): Unable to open '\/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/base.dm': No such file or directory\n06-08 20:53:05.214 W\/ziparchive(19927): Unable to open '\/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/base.dm': No such file or directory\n06-08 20:53:05.317 D\/nativeloader(19927): Configuring classloader-namespace for other apk \/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/base.apk. target_sdk_version=33, uses_libraries=, library_path=\/data\/app\/~~zMAJ3ZlMHKDnoueXu6_p1A==\/github.umer0586.sensorserver-pXSxAeRM3Ix_Xf-yviT0SQ==\/lib\/arm64, permitted_path=\/data:\/mnt\/expand:\/data\/user\/0\/github.umer0586.sensorserver\n06-08 20:53:05.325 V\/GraphicsEnvironment(19927): ANGLE Developer option for 'github.umer0586.sensorserver' set to: 'default'\n06-08 20:53:05.325 V\/GraphicsEnvironment(19927): ANGLE GameManagerService for github.umer0586.sensorserver: false\n06-08 20:53:05.325 V\/GraphicsEnvironment(19927): App is not on the allowlist for updatable production driver.\n06-08 20:53:05.327 D\/NetworkSecurityConfig(19927): No Network Security Config specified, using platform default\n06-08 20:53:05.327 D\/NetworkSecurityConfig(19927): No Network Security Config specified, using platform default\n06-08 20:53:05.340 I\/ACRA (19927): ACRA is enabled for github.umer0586.sensorserver, initializing...\n06-08 20:53:05.398 D\/OplusActivityManager(19927): get AMS extension: android.os.BinderProxy@73fdc2\n06-08 20:53:05.401 D\/OplusGraphicsEvent(19927): OplusGraphicsEventListener create now!\n06-08 20:53:05.401 D\/OplusGraphicsEvent(19927): addEventListener success!\n06-08 20:53:05.403 E\/86.sensorserver(19927): Loaded layer handle (15693940983517848469) for layer \/my_product\/lib64\/[libcolorx-loader.so](http://libcolorx-loader.so/)\n06-08 20:53:05.403 E\/86.sensorserver(19927): Looking for entrypoint ColorX_Check\n06-08 20:53:05.403 E\/86.sensorserver(19927): Found ColorX_Check for \/my_product\/lib64\/[libcolorx-loader.so](http://libcolorx-loader.so/)\n06-08 20:53:05.403 E\/86.sensorserver(19927): Check failed\n06-08 20:53:05.415 D\/AppCompatDelegate(19927): Checking for metadata for AppLocalesMetadataHolderService : Service not found\n06-08 20:53:05.427 I\/oplus.android.OplusFrameworkFactoryImpl(19927): Unknow feature:IOplusTextViewRTLUtilForUG\n06-08 20:53:05.438 D\/ScrollOptimizationHelper(19927): can't find the config file for optimizaiton\n06-08 20:53:05.438 D\/ScrollOptimizationHelper(19927): will not debug for debug is false\n06-08 20:53:05.438 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.438 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.438 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.449 W\/86.sensorserver(19927): Accessing hidden method Landroid\/view\/View;->computeFitSystemWindows(Landroid\/graphics\/Rect;Landroid\/graphics\/Rect;)Z (unsupported, reflection, allowed)\n06-08 20:53:05.449 W\/86.sensorserver(19927): Accessing hidden method Landroid\/view\/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)\n06-08 20:53:05.450 E\/OplusCustomizeRestrictionManager(19927): sInstance is null, start a new sInstance\n06-08 20:53:05.452 D\/CompatibilityChangeReporter(19927): Compat change id reported: 210923482; UID 10731; state: ENABLED\n06-08 20:53:05.460 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.460 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.461 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.461 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.461 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.461 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.469 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.469 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.469 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.472 I\/DynamicFramerate [FRTCConfigManager](19927): initFrameRateConfig: \n06-08 20:53:05.472 I\/DynamicFramerate [FRTCConfigManager](19927): \tlevels: [120, 60, 40, 30]\n06-08 20:53:05.472 I\/DynamicFramerate [FRTCConfigManager](19927): \tthresholds: [400, 80, 30]\n06-08 20:53:05.472 I\/DynamicFramerate [FRTCConfigManager](19927): \tscrollbar fade frame rate: 0\n06-08 20:53:05.472 I\/DynamicFramerate [FRTCConfigManager](19927): FRTCConfigManager: FRTC_CAPABILITY = 120, package name = github.umer0586.sensorserver, PACKAGE_ENABLE = false\n06-08 20:53:05.472 I\/DynamicFramerate [DynamicFrameRateController](19927): init info: mPackageName = github.umer0586.sensorserver, mIsEnabled = false\n06-08 20:53:05.512 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.512 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.512 I\/oplus.android.OplusFrameworkFactoryImpl(19927): get feature:IOplusDynamicVsyncFeature\n06-08 20:53:05.518 D\/AndroidRuntime(19927): Shutting down VM\n06-08 20:53:05.519 E\/AndroidRuntime(19927): FATAL EXCEPTION: main\n06-08 20:53:05.519 E\/AndroidRuntime(19927): Process: github.umer0586.sensorserver, PID: 19927\n06-08 20:53:05.519 E\/AndroidRuntime(19927): java.lang.RuntimeException: Unable to start activity ComponentInfo{github.umer0586.sensorserver\/github.umer0586.sensorserver.activities.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3876)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.os.Looper.loopOnce(Looper.java:240)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.os.Looper.loop(Looper.java:351)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.ActivityThread.main(ActivityThread.java:8399)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat java.lang.reflect.Method.invoke(Native Method)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): Caused by: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat androidx.appcompat.app.AppCompatDelegateImpl.setSupportActionBar(AppCompatDelegateImpl.java:630)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat androidx.appcompat.app.AppCompatActivity.setSupportActionBar(AppCompatActivity.java:185)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat github.umer0586.sensorserver.activities.MainActivity.onCreate(MainActivity.kt:60)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.Activity.performCreate(Activity.java:8422)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.Activity.performCreate(Activity.java:8395)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1403)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3849)\n06-08 20:53:05.519 E\/AndroidRuntime(19927): \t... 12 more\n06-08 20:53:05.519 E\/ACRA (19927): ACRA caught a RuntimeException for github.umer0586.sensorserver\n06-08 20:53:05.519 E\/ACRA (19927): java.lang.RuntimeException: Unable to start activity ComponentInfo{github.umer0586.sensorserver\/github.umer0586.sensorserver.activities.MainActivity}: java.lang.IllegalStateException: This Activity already has an action bar supplied by the window decor. Do not request Window.FEATURE_SUPPORT_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3876)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.os.Handler.dispatchMessage(Handler.java:106)\n06-08 20:53:05.519 E\/ACRA (19927): \tat android.os.Looper.loopOnce(Looper.java:240)\n06-08 20:53:05.519`

**Comment by srbhptl39** [comment]
yes, Verified that its working fine with dark mode disabled

**Comment by umer0586** [comment]
> yes, Verified that its working fine with dark mode disabled. Expecting a release soon with dark mode too

Yes, next release will support dark mode too

**Comment by umer0586** [comment]
App crash now fixed !
