### ISSUE TITLE
Touch screen coordinates as sensor (Enhancement)

### ISSUE THREAD

**Issue by srbhptl39** [umer0586/SensorServer#25]
It would be great to get screen touch points as x, y coordinates in realtime using sockets. 
Additional could be Multi point touch stream.

**Comment by umer0586** [comment]
The app now includes support for a simple touch sensor. If you connect a websocket client to `/touchscreen`, you will receive information about touch actions in a clear format. This information will be in JSON style, like this:
```json
{
 "x" : 23,
 "y" : 100,
 "action" : "ACTION_MOVE or ACTION_UP or ACTION_DOWN"
}
```
- "x" and "y" represents touch coordinates
- "action" can be one of three values:
  - "ACTION_DOWN" indicates that a user has touched the screen.
  - "ACTION_UP" means the user has removed their finger from the screen.
  - "ACTION_MOVE" implies the user is sliding their finger across the screen.

Feature will be available in next release !
