### ISSUE TITLE
Sample rate ignored?

### ISSUE THREAD

**Issue by zenbooster** [umer0586/SensorServer#28]
Why, when I set the sample rate to 500000 microseconds, does the data come in much more often than twice per second?

`websocat.x86_64-pc-windows-gnu.exe ws://192.168.4.44:8080/sensor/connect?type=android.sensor.accelerometer`

```
{"values":[0.251,4.209,5.818],"accuracy":3,"timestamp":1621374624190440}
{"values":[0.366,4.745,4.899],"accuracy":3,"timestamp":1621374645422133}
{"values":[0.481,4.324,3.884],"accuracy":3,"timestamp":1621374666618445}
{"values":[-0.303,6.009,4.573],"accuracy":3,"timestamp":1621374687813666}
{"values":[0.232,5.779,6.891],"accuracy":3,"timestamp":1621374709009359}
{"values":[1.075,4.668,8.347],"accuracy":3,"timestamp":1621374730205508}
{"values":[0.443,4.688,8.845],"accuracy":3,"timestamp":1621374751401281}
{"values":[0.423,4.573,9.189],"accuracy":3,"timestamp":1621374772616441}
{"values":[0.921,4.209,9.879],"accuracy":3,"timestamp":1621374793784571}
{"values":[0.998,4.056,10.224],"accuracy":3,"timestamp":1621374814976873}
{"values":[0.826,4.056,9.975],"accuracy":3,"timestamp":1621374836151340}
{"values":[0.749,4.036,10.128],"accuracy":3,"timestamp":1621374857396960}
{"values":[0.998,4.017,9.783],"accuracy":3,"timestamp":1621374878596889}
{"values":[0.711,4.17,8.538],"accuracy":3,"timestamp":1621374899765047}
{"values":[0.423,4.285,7.466],"accuracy":3,"timestamp":1621374920994965}
{"values":[0.423,4.151,6.968],"accuracy":3,"timestamp":1621374942210585}
{"values":[0.309,3.941,6.738],"accuracy":3,"timestamp":1621374963401508}
{"values":[0.136,3.596,7.676],"accuracy":3,"timestamp":1621374984600364}
{"values":[0.73,3.021,8.787],"accuracy":3,"timestamp":1621375005796903}
{"values":[0.462,2.734,8.462],"accuracy":3,"timestamp":1621375026993143}
{"values":[-0.112,2.389,8.308],"accuracy":3,"timestamp":1621375048188676}
{"values":[0.136,1.834,8.653],"accuracy":3,"timestamp":1621375069382922}
{"values":[0.787,1.067,9.438],"accuracy":3,"timestamp":1621375090584230}
{"values":[0.634,0.569,10.454],"accuracy":3,"timestamp":1621375111785080}
{"values":[0.079,0.32,11.277],"accuracy":3,"timestamp":1621375132985926}
{"values":[-0.016,-0.023,12.484],"accuracy":3,"timestamp":1621375154186403}
{"values":[0.404,-0.464,14.955],"accuracy":3,"timestamp":1621375175386643}
{"values":[1.592,-0.56,16.411],"accuracy":3,"timestamp":1621375196586258}
{"values":[-1.299,0.512,6.91],"accuracy":3,"timestamp":1621375217783643}
{"values":[-0.533,0.455,10.837],"accuracy":3,"timestamp":1621375238983032}
{"values":[-0.054,0.148,10.454],"accuracy":3,"timestamp":1621375260182807}
{"values":[0.098,0.167,9.841],"accuracy":3,"timestamp":1621375281384052}
{"values":[-0.15,0.225,10.109],"accuracy":3,"timestamp":1621375302584903}
{"values":[-0.476,0.263,10.013],"accuracy":3,"timestamp":1621375323785980}
{"values":[-0.131,0.167,10.051],"accuracy":3,"timestamp":1621375344986980}
{"values":[-0.15,0.206,10.013],"accuracy":3,"timestamp":1621375366187369}
{"values":[-0.15,0.206,10.051],"accuracy":3,"timestamp":1621375387387835}
{"values":[-0.131,0.206,10.051],"accuracy":3,"timestamp":1621375408588686}
{"values":[-0.189,0.206,10.013],"accuracy":3,"timestamp":1621375429788153}
{"values":[-0.15,0.206,9.994],"accuracy":3,"timestamp":1621375450988065}
{"values":[-0.169,0.167,10.09],"accuracy":3,"timestamp":1621375472185911}
{"values":[-0.15,0.206,10.051],"accuracy":3,"timestamp":1621375493382137}
{"values":[-0.15,0.206,10.051],"accuracy":3,"timestamp":1621375514574829}
{"values":[-0.169,0.167,10.032],"accuracy":3,"timestamp":1621375535772147}
{"values":[-0.208,0.206,10.032],"accuracy":3,"timestamp":1621375556970696}
{"values":[-0.169,0.186,10.071],"accuracy":3,"timestamp":1621375578170768}
```

**Comment by umer0586** [comment]
> The data delay (or sampling rate) controls the interval at which sensor events are sent to your application via the [onSensorChanged()](https://developer.android.com/reference/android/hardware/SensorEventListener#onSensorChanged(android.hardware.SensorEvent)) callback method. The default data delay is suitable for monitoring typical screen orientation changes and uses a delay of 200,000 microseconds. You can specify other data delays, such as [SENSOR_DELAY_GAME](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_GAME) (20,000 microsecond delay), [SENSOR_DELAY_UI](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_UI) (60,000 microsecond delay), or [SENSOR_DELAY_FASTEST](https://developer.android.com/reference/android/hardware/SensorManager#SENSOR_DELAY_FASTEST) (0 microsecond delay). As of Android 3.0 (API Level 11) you can also specify the delay as an absolute value (in microseconds).
> 
> The delay that you specify is only a suggested delay. The Android system and other applications can alter this delay. As a best practice, you should specify the largest delay that you can because the system typically uses a smaller delay than the one you specify (that is, you should choose the slowest sampling rate that still meets the needs of your application). Using a larger delay imposes a lower load on the processor and therefore uses less power.
> 
> There is no public method for determining the rate at which the sensor framework is sending sensor events to your application; however, you can use the timestamps that are associated with each sensor event to calculate the sampling rate over several events. You should not have to change the sampling rate (delay) once you set it. If for some reason you do need to change the delay, you will have to unregister and reregister the sensor listener.

source [https://developer.android.com/guide/topics/sensors/sensors_overview](https://developer.android.com/guide/topics/sensors/sensors_overview)

For fastest sampling, set rate to 0 (before starting a server)
