### ISSUE TITLE
Hi ; FAILURE: Build failed with an exception.   can you help me. thanks

### ISSUE THREAD

**Issue by mvwtest** [umer0586/SensorServer#3]
hello, i use this Action build  your project, but  i got this:
FAILURE: Build failed with an exception.   can you help me. thanks

my workflows file:
https://github.com/mvwtest/SensorServer/blob/main/.github/workflows/SensorServer.yml

and biuld log:
https://github.com/mvwtest/SensorServer/runs/4952176375?check_suite_focus=true

how can i do it? thank you.

**Comment by mvwtest** [comment]
Yes,I got it. You are great.thanks.

**Comment by mvwtest** [comment]
Asol ,will you contemplate add Bluetooth-uart or usb serial ?

**Comment by umer0586** [comment]
> Yes,I got it. You are great.thanks.

@mvwtest Glad to know you solved the issue by yourself. so what was the cause ?

**Comment by umer0586** [comment]
> Asol ,will you contemplate add Bluetooth-uart or usb serial ?

USB using ABD has already been added to the app
