### ISSUE TITLE
Cannot read GPS data

### ISSUE THREAD

**Issue by Manouel96** [umer0586/SensorServer#60]
When I am trying to read the GPS data with websocket with python, showing the gps is connected both on the server app and the terminal app but no data is coming out.
The GPS permission is allowed in the app settings, and the GPS is on. 

![Capture](https://github.com/umer0586/SensorServer/assets/120972304/d00a036c-6ef5-4df4-95d9-2fb544739f0f)

The full code:

import websocket
import json

def on_message(ws, message):
    data = json.loads(message)
    x = data["longitude"] 
    
    print("x = ", x)

def on_error(ws, error):
    print("error occurred ", error)
    
def on_close(ws, close_code, reason):
    print("connection closed : ", reason)
    
def on_open(ws):
    print("connected")
    

def connect(url):
    ws = websocket.WebSocketApp(url,
                              on_open=on_open,
                              on_message=on_message,
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever()
 
 
connect("ws://172.20.10.2:8080/gps")

**Comment by umer0586** [comment]
Connected clients receive updates about your GPS location only **when your location changes**. This means you'll need to be **moving** (in an open area) to trigger updates.

**Comment by Manouel96** [comment]
Hi @umer0586, got it, is there a way to stream real time GPS coordination continuously without moving and triggering? 
Overall, the application is working great, and I am able to read all of the sensors data with websocket, great work!

Cheers,
Manouel

**Comment by umer0586** [comment]
> is there a way to stream real time GPS coordination continuously without moving and triggering?

Currently, the app does not support sending GPS coordinates to connected clients while standing still. I will look into this and plan to add this functionality in a future release of the app.

**Comment by Manouel96** [comment]
That will be a great feature, please let me know if I can modify some code to do it, or I will just wait for the future updates, thanks for the quick response!

**Comment by umer0586** [comment]
The Android GPS API includes the method [getLastKnownLocation()](https://developer.android.com/reference/android/location/LocationManager.html#getLastKnownLocation(java.lang.String)), which returns the last known location from the specified provider (GPS or Network). I am considering adding functionality that allows a connected client to call this method in a following manner.

```python
import websocket
import json
from time import sleep


def on_message(ws, message):
    location_data = json.loads(message)

def on_error(ws, error):
    print("error occurred ", error)
    
def on_close(ws, close_code, reason):
    print("connection closed : ", reason)
    
def on_open(ws):
    print("connected")
   # request last known location every 100 milisecconds
   while True:
       ws.send("getLastKnownLocation") # will trigger ws.onMessage
       sleep(0.1)
    

def connect(url):
    ws = websocket.WebSocketApp(url,
                              on_open=on_open,
                              on_message=on_message,
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever()
 
 
connect("ws://192.168.0.103:8080/sensor/gps") 

```

**Comment by umer0586** [comment]
Feature added see [Getting Data From GPS](https://github.com/umer0586/SensorServer/wiki/Getting-Data-From-GPS)
