### ISSUE TITLE
"this site can't be reached"

### ISSUE THREAD

**Issue by Jcdov** [umer0586/SensorServer#9]
The webpage at ws://*myphone'sip*:8081/sensor/connect?type=android.sensor.rotation_vector might be temporarily down or it may have moved permanently to a new web address. and i get code ERR_UNKNOWN_URL_SCHEME. what can i do about this?

**Comment by umer0586** [comment]
It seems that you are typing websocket URL in the browser's address bar, which is obviously not the way to connect to websocket server.

**Comment by Dantrix846** [comment]
well i figured it out, sorry for not letting you know. I just turned server
on and off until it showed up number starting with 192 instead of 172

út 1. 11. 2022 v 2:43 odesílatel Umer Farooq ***@***.***>
napsal:
